name: Test Scoop Manifests

on:
  # pull_request:
  #   branches: [main]
  push:
    branches: [main]

jobs:
  Test:
    strategy:
      matrix:
        manifest: [azddns, azfwrmgr, azsqlidxmgr]
        # https://github.blog/changelog/2025-04-14-windows-arm64-hosted-runners-now-available-in-public-preview
        os:
          - windows-latest
          - windows-11-arm

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Scoop Bucket
        uses: actions/checkout@v4

      - name: Install Scoop
        run: |
          iwr -useb get.scoop.sh | iex
          echo "$HOME\scoop\shims" | Out-File -Append -Encoding ASCII $env:GITHUB_PATH

      - name: Install from local manifest
        run: scoop install .\${{ matrix.manifest }}.json

      - name: Run tool tests
        run: ${{ matrix.manifest }} --version && ${{ matrix.manifest }} --help
